### ISSUE TITLE
Correção de responsividade - Sprint 1

### ISSUE THREAD

**Issue by Escowolf** [Escowolf/rota-ativa-pads#24]
[x] Estudar a estrutura do frontend; @JohnRSS 
[x] Aplicar responsividade nas páginas de login, home, cadastro de vagas; @JohnRSS 
[x] Prototipar páginas no Figma; @JohnRSS 
[x] Alterar e preparar o pitch do projeto @BeatrizBottai 
[x] Testar projeto web e definir correções @BeatrizBottai & @Escowolf 
[x] Corrigir services front @Escowolf

**Comment by Escowolf** [comment]
Limpeza de código do front; 
Renomear termos para evitar redundância no código e facilitar a leitura;
Produção de casos de uso para teste @BeatrizBottai;

**Comment by BeatrizBottai** [comment]
Link canva: [https://www.canva.com/design/DAF0u8cIRQs/SCIu1PENJnRpTDSdvJ-aig/edit](url)

**Comment by JohnRSS** [comment]
Prototipagem das telas de Login e Cadastro;
Estudo do código;
